apiVersion: v1
kind: Service
metadata:
  name: agromind-serving
  namespace: team

spec:
  type: NodePort

  selector:
    app: agromind-vllm

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000